---
- hosts: l1-2
  become: yes
  become_user: root
  become_method: sudo
  tasks:
      - name: Provisioning physical and logical ports
        nclu:
          commands:
            - add hostname L1-2
            - add loopback lo ip address 192.0.2.4/32
            - add loopback lo ipv6 address 2001:db8::4/128
            - add interface swp1 post-up echo 1 > /proc/sys/net/ipv4/conf/swp1/proxy_arp
            - add interface swp2 post-up echo 1 > /proc/sys/net/ipv4/conf/swp2/proxy_arp
            - add interface swp1 ip address 192.0.2.14/30
            - add interface swp1 ipv6 address 2001:db8:3::2/64
            - add interface swp1 alias "UPLINK-L1-1-SWP1"
            - add interface swp1 mtu 9018
            - add interface swp2 ip address 192.0.2.17/30
            - add interface swp2 ipv6 address 2001:db8:5::1/64
            - add interface swp2 alias "UPLINK-L4-SWP1"
            - add interface swp2 mtu 9018
          commit: true
      - name: Enable BGP
        nclu:
          commands:
            - add bgp autonomous-system 64498
            - add bgp router-id 192.0.2.4
          commit: true
      - name: Configure BGP
        nclu:
          commands:
            - add bgp neighbor L1 peer-group
            - add bgp neighbor L1 password VerySecure
            - add bgp neighbor L1 bfd
            - add bgp neighbor L1 remote-as 64498
            - add bgp neighbor L1-V6 peer-group
            - add bgp neighbor L1-V6 password VerySecure
            - add bgp neighbor L1-V6 bfd
            - add bgp neighbor L1-V6 remote-as 64498
            - add bgp neighbor L4 peer-group
            - add bgp neighbor L4 password VerySecure
            - add bgp neighbor L4 bfd
            - add bgp neighbor L4 remote-as 64501
            - add bgp neighbor L4-V6 peer-group
            - add bgp neighbor L4-V6 password VerySecure
            - add bgp neighbor L4-V6 bfd
            - add bgp neighbor L4-V6 remote-as 64501
            - add bgp neighbor 192.0.2.13 peer-group L1
            - add bgp neighbor 2001:db8:3::1 peer-group L1-V6
            - add bgp neighbor 192.0.2.18 peer-group L4
            - add bgp neighbor 2001:db8:5::2 peer-group L4-V6
            - add bgp ipv6 unicast neighbor L1-V6 activate
            - add bgp ipv6 unicast neighbor L4-V6 activate
            - add bgp ipv4 unicast neighbor L1 activate
            - add bgp ipv4 unicast neighbor L4 activate
            - del bgp ipv4 unicast neighbor 2001:db8:3::1 activate
            - del bgp ipv4 unicast neighbor 2001:db8:5::2 activate
            - add bgp l2vpn evpn neighbor L1 activate
            - add bgp l2vpn evpn neighbor L4 activate
            - add bgp ipv4 unicast redistribute connected
            - add bgp ipv6 unicast redistribute connected
            - add bgp ipv4 unicast redistribute static
            - add bgp ipv6 unicast redistribute static
          commit: true
